name: test-action
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: jojobean13/github-action-test@v1.2
        with:
          who-to-greet: 'Jo the Dev'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
